server:
  port: 8080
spring:
  output:
    ansi:
      enabled: always
  datasource:
    username: root
    password: xxx
    url: jdbc:mysql://xxx:3306/forum?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
# mybatis 扫包
mybatis:
  mapper-locations:
    classpath*: mapper/*.xml
  # 开启驼峰命名转换
  configuration:
    map-underscore-to-camel-case: true
